### ISSUE TITLE
Areas with 2 objectives cause freeze/lock

### ISSUE THREAD

**Issue by Mercurian** [Darkdoom22/AutoUNM#1]
Any area that has two pops causes it to freeze.

I tried to do Myuufah but even using /unm start obj1 it froze and I'm told that obj2 freezes it too, but I haven't tried

**Comment by Darkdoom22** [comment]
Obj1 works correctly for Mhuufya, in Wajaom obj2 should be Tinnin.  Which Ethereal Junction was this at?

**Comment by Mercurian** [comment]
The junction where normal Zoral Ja's pops

It froze when I tried it, only bothered the once since there's no great way to easy farm myuufa
