### ISSUE TITLE
Menu lockup

### ISSUE THREAD

**Issue by Heretic6667** [Darkdoom22/AutoUNM#4]
If the addon is loaded and the Ethereal Junction is manually selected, the vanilla menu fails to load.  The only way to get unstuck out of this menu-less window is to //terminate or otherwise close & reload FFXI.  Simple solution is just not manually clicking the junction while the addon is loaded, but if anything can be added to get around this that would be fantastic.

**Comment by Darkdoom22** [comment]
newest commit will fix this, as well as an unrelated issue I hadn't noticed before where you would lock on any user interaction (not just on junctions)

also added a new command to release you from being stuck just in case, //unm stuck will release you.

tyty!
