### ISSUE TITLE
Stuck "Waiting on Respawn"

### ISSUE THREAD

**Issue by Heretic6667** [Darkdoom22/AutoUNM#5]
I'm unable to recreate this on demand, but the issue has occurred more than once where the addon will fail to spawn the UNM.

The bot status will read: Waiting on Respawn.  The Ethereal Junction is in plain reach of my character and I'm able to access the Junction's menu, allowing to me still manually pop the UNM.

During combat of the manually spawned UNM the bot status updates to: In Combat

When the manually spawned UNM is defeated, the bot status returns to Waiting on Respawn and fails to fail the UNM when the Ethereal Junction returns.  The loop continues.

P.S. to be clear, I'm popping in Sea Serpent's Grotto; //unm start obj1

**Comment by Darkdoom22** [comment]
So far unable to recreate on the junction at J-7 in SSG, if you're able to figure out how to recreate it please do let me know how and I will find out what's going on.

**Comment by Darkdoom22** [comment]
@Tathamet667

Just released a new version of the addon that should fix this issue: https://github.com/Darkdoom22/autounm4
